### ISSUE TITLE
Howto?

### ISSUE THREAD

**Issue by xophe86** [chrisjohndigital/OpenLang#1]
Hello,
Nice project! But how does it work? I download the source but do not understand how to test/use it. What is the first file to launch through the Internet browser to get it work?
Regards,

**Comment by chrisjohndigital** [comment]
Hi xophe86, instructions:

1) Install Node.js from nodejs.org
2) Download or clone the OpenLang repo locally
3) Using a cli run **npm install** on the repo
4) Using a cli run **npm start** on the repo

The app will then run on localhost port 3000.

Cheers, Chris.
